language: php

sudo: false

php:
  - "5.4"
  - "5.5"
  - "5.6"

install:
  - rm -rf build && mkdir -p build/logs build/pdepend build/coverage
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --log-junit=build/logs/junit.xml --coverage-text --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=vendor/novactive/phpcs-novastandards/src/NovaPSR2 src/
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming
  - ./vendor/bin/phpcpd src

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - ./vendor/bin/coveralls

