language: php

php:
  - "5.4"
  - "5.5"

install:
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming
  - ./vendor/bin/phpcpd src

after_script:  
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

